# Intro to Data Science with Pokemon

Arrays
food = ['Ham', 'cheese', 'bread', 'mayo', 'lettuce', 'tomatoes']
print(food)
['Ham', 'cheese', 'bread', 'mayo', 'lettuce', 'tomatoes']
print(food[5])
tomatoes
sliced_food = food[0:3]
print(sliced_food)
['Ham', 'cheese', 'bread']
Import Libraries

import pandas as pd
import numpy as py
import seaborn as sb
print("PANDAS version " + pd.__version__ )
print("numpy version " + py.__version__)
print("seaborn version " + sb.__version__)
PANDAS version 2.1.3
numpy version 1.26.2
seaborn version 0.13.0
Loading Data

df = pd.read_csv('pokemon.csv')
Displaying Full Data Frames

#pd.set_option('display.max_rows', None)
df.head(700)

In [63]: In [64]: In [65]: In [66]: In [67]: In [68]: In [69]: In [70]: In [71]: In [72]:

Per Nat Pokemon HP Atk Def SpA SpD Spe Total ... Catch EXP
0 1.0 1.0 Bulbasaur 45 49 49 65 65 45 318 ... 45 1059860
1 2.0 2.0 Ivysaur 60 62 63 80 80 60 405 ... 45 1059860
2 3.0 3.0 Venusaur 80 82 83 100 100 80 525 ... 45 1059860
3 4.0 4.0 Charmander 39 52 43 60 50 65 309 ... 45 1059860
4 5.0 5.0 Charmeleon 58 64 58 80 65 80 405 ... 45 1059860
... ... ... ... ... ... ... ... ... ... ... ... ... ...
658 646.0 646.0 Kyurem 125 130 90 130 90 95 660 ... 3 1250000
659 647.0 647.0 Keldeo 91 72 90 129 90 108 580 ... 3 1250000
660 648.0 648.0 Meloetta

(A) 100 77 77 128 128 90 600 ... 3 1250000
661 648.1 648.1 Meloetta (P) 100 128 90 77 77 128 600 ... 3 1250000
662 649.0 649.0 Genesect 71 120 95 120 95 99 600 ... 3 1250000
663 rows × 35 columns

# Accessing Columns

df.Pokemon
0 Bulbasaur
1 Ivysaur
2 Venusaur
3 Charmander
4 Charmeleon
...
658 Kyurem
659 Keldeo
660 Meloetta (A)
661 Meloetta (P)
662 Genesect
Name: Pokemon, Length: 663, dtype: object
df.Pokemon[0]
'Bulbasaur'
df.Pokemon[0:10]

Out[72]: In [73]: Out[73]: In [74]: Out[74]: In [75]:

0 Bulbasaur
1 Ivysaur
2 Venusaur
3 Charmander
4 Charmeleon
5 Charizard
6 Squirtle
7 Wartortle
8 Blastoise
9 Caterpie
Name: Pokemon, dtype: object
Accessing Multiple Columns

You can access multiple columns, using a variable
pokemon_Atk_HP = df[['Pokemon', 'HP', 'Atk']]
pokemon_Atk_HP.head(10)
Pokemon HP Atk
0 Bulbasaur 45 49
1 Ivysaur 60 62
2 Venusaur 80 82
3 Charmander 39 52
4 Charmeleon 58 64
5 Charizard 78 84
6 Squirtle 44 48
7 Wartortle 59 63
8 Blastoise 79 83
9 Caterpie 45 30

# Accessing Rows

You can access rows by using iloc[] which allows you to specify and index location for a
row
specific_row = df.iloc[0]
print(specific_row)

Out[75]: In [76]: In [77]: Out[77]: In [79]: In [80]:

Per 1.0
Nat 1.0
Pokemon Bulbasaur
HP 45
Atk 49
Def 49
SpA 65
SpD 65
Spe 45
Total 318
Type I Grass
Type II Poison
Tier NU
Ability I Overgrow
Ability II NaN
Hidden Ability Chlorophyll
Mass 6.9 kG
LK/GK 20
EV Worth 1 SpA
EXPV 64
Color Green
Hatch 5120
Gender M (87.5%)
Egg Group I Monster
Egg Group II Grass
Catch 45
EXP 1059860
Evolve NaN
Per.1 1.0
Nat.1 1.0
Joh 226.0
Hoe NaN
Sin NaN
Un NaN
Pokemon.1 Bulbasaur
Name: 0, dtype: object
Slicing Rows and Columns

Note that when slicing if I return 0:10 I am going to get indexes 0-9
rows_zero_to_ten = df.iloc[0:10]
rows_zero_to_ten.head(10)

In [81]: In [82]:

Per Nat Pokemon HP Atk Def SpA SpD Spe Total ... Catch EXP Evolv
0 1.0 1.0 Bulbasaur 45 49 49 65 65 45 318 ... 45 1059860 Na
1 2.0 2.0 Ivysaur 60 62 63 80 80 60 405 ... 45 1059860 Lv. 1
2 3.0 3.0 Venusaur 80 82 83 100 100 80 525 ... 45 1059860 Lv. 3
3 4.0 4.0 Charmander 39 52 43 60 50 65 309 ... 45 1059860 Na
4 5.0 5.0 Charmeleon 58 64 58 80 65 80 405 ... 45 1059860 Lv. 1
5 6.0 6.0 Charizard 78 84 78 109 85 100 534 ... 45 1059860 Lv. 3
6 7.0 7.0 Squirtle 44 48 65 60 54 43 314 ... 45 1059860 Na
7 8.0 8.0 Wartortle 59 63 80 65 80 58 405 ... 45 1059860 Lv. 1
8 9.0 9.0 Blastoise 79 83 100 85 105 78 530 ... 45 1059860 Lv. 3
9 10.0 10.0 Caterpie 45 30 35 20 20 45 195 ... 255 1000000 Na
10 rows × 35 columns

# Useful PANDAS Methods

df.Pokemon.sort_values() #sorts values of pokemon column
464 Abomasnow
62 Abra
358 Absol
629 Accelgor
141 Aerodactyl
...
262 Zigzagoon
583 Zoroark
582 Zorua
40 Zubat
646 Zweilous
Name: Pokemon, Length: 663, dtype: object
df.Pokemon[0:10].sort_values() #sorts value of first 9 rows

Out[82]: In [83]: Out[83]: In [84]:

8 Blastoise
0 Bulbasaur
9 Caterpie
5 Charizard
3 Charmander
4 Charmeleon
1 Ivysaur
6 Squirtle
2 Venusaur
7 Wartortle
Name: Pokemon, dtype: object
df.HP.mean() #gets mean
68.34087481146305
df.SpA.describe()
count 663.000000
mean 68.962293
std 29.246841
min 10.000000
25% 45.000000
50% 65.000000
75% 90.000000
max 180.000000
Name: SpA, dtype: float64
Filtering Data

Filtering data is critical to working with data and making it readable for many different uses.
Filtering uses operators to do this along with other common programming concepts.
chu_pokemon = df[df['Pokemon'].str.contains("chu")]
print(chu_pokemon)
Per Nat Pokemon HP Atk Def SpA SpD Spe Total ... Catch \
24 26.0 25.0 Pikachu 35 55 30 50 40 90 300 ... 190
25 27.0 26.0 Raichu 60 90 55 90 80 100 475 ... 75
171 25.0 172.0 Pichu 20 40 15 35 35 60 205 ... 190
237 143.0 238.0 Smoochum 45 30 15 85 65 65 305 ... 45
EXP Evolve Per.1 Nat.1 Joh Hoe Sin Un Pokemon.1
24 1000000 Friendship 26.0 25.0 22.0 156.0 104.0 NaN Pikachu
25 1000000 Thunderstone 27.0 26.0 23.0 157.0 105.0 NaN Raichu
171 1000000 NaN 25.0 172.0 21.0 155.0 103.0 NaN Pichu
237 1000000 NaN 143.0 238.0 152.0 NaN NaN NaN Smoochum
[4 rows x 35 columns]
special_attack_70 = df[df["SpA"]== 70]

Out[84]: In [22]: Out[22]: In [23]: Out[23]: In [85]: In [86]: In [26]:

In [27]:

print(special_attack_70)

Per Nat Pokemon HP Atk Def SpA SpD Spe Total ... Catch \
17 18.0 18.0 Pidgeot 83 80 75 70 70 91 469 ... 45
57 63.0 58.0 Growlithe 55 70 45 70 50 60 350 ... 190
61 67.0 62.0 Poliwrath 90 85 95 70 90 70 500 ... 45
68 75.0 69.0 Bellsprout 50 75 35 70 30 40 300 ... 255
86 95.0 87.0 Dewgong 90 70 80 70 95 70 475 ... 75
115 132.0 116.0 Horsea 30 40 70 70 25 60 295 ... 225
119 137.0 120.0 Staryu 30 45 55 70 55 85 340 ... 225
147 179.0 148.0 Dragonair 61 84 65 70 70 70 420 ... 45
168 46.0 169.0 Crobat 85 90 80 70 80 130 535 ... 90
176 205.0 177.0 Natu 40 50 45 70 45 70 320 ... 190
217 248.0 218.0 Slugma 40 40 40 70 40 20 250 ... 190
239 148.0 240.0 Magby 45 75 37 70 55 83 365 ... 45
254 279.0 255.0 Torchic 45 60 40 70 50 45 310 ... 45
319 347.0 320.0 Wailmer 130 70 35 70 35 60 400 ... 125
324 352.0 325.0 Spoink 60 25 35 70 80 60 330 ... 255
333 361.0 334.0 Altaria 75 70 90 70 105 80 490 ... 45
343 371.0 344.0 Claydol 60 70 105 70 120 75 500 ... 90
347 375.0 348.0 Armaldo 75 125 100 70 80 45 495 ... 45
350 378.0 351.0 Castform 70 70 70 70 70 70 420 ... 45
387 415.2 386.2 Deoxys (D) 50 70 160 70 160 90 600 ... 3
443 139.0 439.0 Mime Jr. 20 25 45 70 90 60 310 ... 145
477 252.0 473.0 Mamoswine 110 130 80 70 60 80 530 ... 50
510 499.0 499.0 Pignite 90 93 55 70 55 55 418 ... 45
553 542.0 542.0 Leavanny 75 103 80 70 70 92 490 ... 45
559 548.0 548.0 Petilil 45 35 50 70 50 30 280 ... 190
612 600.0 600.0 Klang 60 80 95 70 85 50 440 ... 60
613 601.0 601.0 Klinklang 60 100 115 70 85 90 520 ... 30
626 614.0 614.0 Beartic 95 110 80 70 80 50 485 ... 60
EXP Evolve Per.1 Nat.1 Joh Hoe Sin Un \
17 1059860 Lv. 36 18.0 18.0 12.0 NaN NaN NaN
57 1250000 NaN 63.0 58.0 127.0 NaN NaN NaN
61 1059860 Water Stone 67.0 62.0 74.0 NaN NaN NaN
68 1059860 NaN 75.0 69.0 64.0 NaN NaN NaN
86 1000000 Lv. 34 95.0 87.0 177.0 NaN NaN NaN
115 1000000 NaN 132.0 116.0 186.0 184.0 NaN NaN
119 1250000 NaN 137.0 120.0 167.0 143.0 NaN NaN
147 1250000 Lv. 30 179.0 148.0 242.0 NaN NaN NaN
168 1000000 Friendship 46.0 169.0 39.0 65.0 30.0 NaN
176 1000000 NaN 205.0 177.0 159.0 162.0 NaN NaN
217 1000000 NaN 248.0 218.0 211.0 103.0 NaN NaN
239 1000000 NaN 148.0 240.0 150.0 NaN 200.0 NaN
254 1059860 NaN 279.0 255.0 NaN 4.0 NaN NaN
319 1640000 NaN 347.0 320.0 NaN 99.0 NaN NaN
324 800000 NaN 352.0 325.0 NaN 110.0 NaN NaN
333 600000 Lv. 35 361.0 334.0 NaN 122.0 172.0 NaN
343 1000000 Lv. 36 371.0 344.0 NaN 132.0 NaN NaN
347 600000 Lv. 40 375.0 348.0 NaN 136.0 NaN NaN
350 1000000 N 378.0 351.0 NaN 142.0 NaN NaN
387 1250000 N 415.2 386.2 NaN 202.2 NaN NaN
443 1000000 NaN 139.0 439.0 NaN NaN 94.0 NaN
477 1250000 Level w/ Ancientpower 252.0 473.0 NaN NaN 205.0 NaN
510 1059860 Lv. 17 499.0 499.0 NaN NaN NaN 5.0
553 1059860 Friendship 542.0 542.0 NaN NaN NaN 48.0
559 1000000 NaN 548.0 548.0 NaN NaN NaN 54.0

612 1059860 Lv. 38 600.0 600.0 NaN NaN NaN 106.0
613 1059860 Lv. 49 601.0 601.0 NaN NaN NaN 107.0
626 1000000 Lv. 37 614.0 614.0 NaN NaN NaN 120.0
Pokemon.1
17 Pidgeot
57 Growlithe
61 Poliwrath
68 Bellsprout
86 Dewgong
115 Horsea
119 Staryu
147 Dragonair
168 Crobat
176 Natu
217 Slugma
239 Magby
254 Torchic
319 Wailmer
324 Spoink
333 Altaria
343 Claydol
347 Armaldo
350 Castform
387 Deoxys (D)
443 Mime Jr.
477 Mamoswine
510 Pignite
553 Leavanny
559 Petilil
612 Klang
613 Klinklang
626 Beartic
[28 rows x 35 columns]
Filtering with Logical Operators

water_high_speed = df[(df["Spe"] > 100) & (df['Type I'] == "Water")]
print(water_high_speed)